from typing import Any


class Canvas:
    def SetImage(
        self,
        image: Any,
        offset_x: int = 0,
        offset_y: int = 0,
        unsafe: bool = True,
    ) -> None: ...
    def SetPixelsPillow(
        self,
        xstart: int,
        ystart: int,
        width: int,
        height: int,
        image_capsule: object,
    ) -> None: ...


class FrameCanvas(Canvas):
    def Fill(self, red: int, green: int, blue: int) -> None: ...
    def Clear(self) -> None: ...
    def SetPixel(self, x: int, y: int, red: int, green: int, blue: int) -> None: ...

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def pwmBits(self) -> int: ...
    @pwmBits.setter
    def pwmBits(self, pwmBits: int) -> None: ...

    @property
    def brightness(self) -> int: ...
    @brightness.setter
    def brightness(self, val: int) -> None: ...


class RGBMatrixOptions:
    @property
    def hardware_mapping(self) -> str: ...
    @hardware_mapping.setter
    def hardware_mapping(self, value: str) -> None: ...

    @property
    def rows(self) -> int: ...
    @rows.setter
    def rows(self, value: int) -> None: ...

    @property
    def cols(self) -> int: ...
    @cols.setter
    def cols(self, value: int) -> None: ...

    @property
    def chain_length(self) -> int: ...
    @chain_length.setter
    def chain_length(self, value: int) -> None: ...

    @property
    def parallel(self) -> int: ...
    @parallel.setter
    def parallel(self, value: int) -> None: ...

    @property
    def pwm_bits(self) -> int: ...
    @pwm_bits.setter
    def pwm_bits(self, value: int) -> None: ...

    @property
    def pwm_lsb_nanoseconds(self) -> int: ...
    @pwm_lsb_nanoseconds.setter
    def pwm_lsb_nanoseconds(self, value: int) -> None: ...

    @property
    def brightness(self) -> int: ...
    @brightness.setter
    def brightness(self, value: int) -> None: ...

    @property
    def scan_mode(self) -> int: ...
    @scan_mode.setter
    def scan_mode(self, value: int) -> None: ...

    @property
    def multiplexing(self) -> int: ...
    @multiplexing.setter
    def multiplexing(self, value: int) -> None: ...

    @property
    def row_address_type(self) -> int: ...
    @row_address_type.setter
    def row_address_type(self, value: int) -> None: ...

    @property
    def disable_hardware_pulsing(self) -> bool: ...
    @disable_hardware_pulsing.setter
    def disable_hardware_pulsing(self, value: bool) -> None: ...

    @property
    def show_refresh_rate(self) -> bool: ...
    @show_refresh_rate.setter
    def show_refresh_rate(self, value: bool) -> None: ...

    @property
    def inverse_colors(self) -> bool: ...
    @inverse_colors.setter
    def inverse_colors(self, value: bool) -> None: ...

    @property
    def led_rgb_sequence(self) -> str: ...
    @led_rgb_sequence.setter
    def led_rgb_sequence(self, value: str) -> None: ...

    @property
    def pixel_mapper_config(self) -> str: ...
    @pixel_mapper_config.setter
    def pixel_mapper_config(self, value: str) -> None: ...

    @property
    def panel_type(self) -> str: ...
    @panel_type.setter
    def panel_type(self, value: str) -> None: ...

    @property
    def pwm_dither_bits(self) -> int: ...
    @pwm_dither_bits.setter
    def pwm_dither_bits(self, value: int) -> None: ...

    @property
    def limit_refresh_rate_hz(self) -> int: ...
    @limit_refresh_rate_hz.setter
    def limit_refresh_rate_hz(self, value: int) -> None: ...

    @property
    def gpio_slowdown(self) -> int: ...
    @gpio_slowdown.setter
    def gpio_slowdown(self, value: int) -> None: ...

    @property
    def rp1_rio(self) -> int: ...
    @rp1_rio.setter
    def rp1_rio(self, value: int) -> None: ...

    @property
    def daemon(self) -> int: ...
    @daemon.setter
    def daemon(self, value: int) -> None: ...

    @property
    def drop_privileges(self) -> int: ...
    @drop_privileges.setter
    def drop_privileges(self, value: int) -> None: ...

    @property
    def drop_priv_user(self) -> str: ...
    @drop_priv_user.setter
    def drop_priv_user(self, value: str) -> None: ...

    @property
    def drop_priv_group(self) -> str: ...
    @drop_priv_group.setter
    def drop_priv_group(self, value: str) -> None: ...


class RGBMatrix(Canvas):
    def __init__(
        self,
        rows: int = 0,
        chains: int = 0,
        parallel: int = 0,
        options: RGBMatrixOptions | None = None,
    ) -> None: ...
    def Fill(self, red: int, green: int, blue: int) -> None: ...
    def SetPixel(self, x: int, y: int, red: int, green: int, blue: int) -> None: ...
    def Clear(self) -> None: ...
    def CreateFrameCanvas(self) -> FrameCanvas: ...
    def SwapOnVSync(
        self,
        newFrame: FrameCanvas,
        framerate_fraction: int = 1,
    ) -> FrameCanvas: ...

    @property
    def luminanceCorrect(self) -> bool: ...
    @luminanceCorrect.setter
    def luminanceCorrect(self, luminanceCorrect: bool) -> None: ...

    @property
    def pwmBits(self) -> int: ...
    @pwmBits.setter
    def pwmBits(self, pwmBits: int) -> None: ...

    @property
    def brightness(self) -> int: ...
    @brightness.setter
    def brightness(self, brightness: int) -> None: ...

    @property
    def height(self) -> int: ...

    @property
    def width(self) -> int: ...
