from .core import Canvas


class Color:
    def __init__(self, red: int = 0, green: int = 0, blue: int = 0) -> None: ...

    @property
    def red(self) -> int: ...
    @red.setter
    def red(self, value: int) -> None: ...

    @property
    def green(self) -> int: ...
    @green.setter
    def green(self, value: int) -> None: ...

    @property
    def blue(self) -> int: ...
    @blue.setter
    def blue(self, value: int) -> None: ...


class Font:
    def CharacterWidth(self, char: int) -> int: ...
    def LoadFont(self, file: str) -> None: ...
    def DrawGlyph(self, c: Canvas, x: int, y: int, color: Color, char: int) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def baseline(self) -> int: ...


def DrawText(c: Canvas, f: Font, x: int, y: int, color: Color, text: str) -> int: ...
def DrawCircle(c: Canvas, x: int, y: int, r: int, color: Color) -> None: ...
def DrawLine(
    c: Canvas,
    x1: int,
    y1: int,
    x2: int,
    y2: int,
    color: Color,
) -> None: ...
